S2 12 add signup
WildCodeSchool-2023-09/php-p2-strasbouq pull request #6
Opened 2023-11-07 11:28 UTC by Sinezis

Ajout des pages login, signup et contact

2023-11-07 11:37 UTC, Jeynox requested changes
Super travail, mais changements de nom de classe a changer pour éviter les conflits dans le CSS, ajout des name dans les forms a faire

2023-11-08 07:55 UTC, Dev-Djam approved these changes

2023-11-08 09:40 UTC, yavuzkutuk commented
@Sinezis tu peux dire à ta team de faire des reviews

2023-11-08 15:48 UTC, Jeynox approved these changes
Super tu as géré

2023-11-08 15:49 UTC, DaniletDorian approved these changes
Bien joué

2023-11-08 20:50 UTC, vincentr-wcs commented
@Sinezis il faut régler les conflits avant notre review :)

2023-11-08 21:59 UTC, vincentr-wcs requested changes
Deux trois changements à faire et ça sera good ;)

2023-11-08 21:59 UTC, vincentr-wcs commented on public/assets/css/contact.css
> +    font-size: 80px;
C'est mieux pour que le texte soit responsive de mettre en rem

2023-11-08 21:59 UTC, vincentr-wcs commented on public/assets/css/contact.css
> +    background-color: #132028;
Tu as des variables de disponibles dans root.css et tu les utilises pas ..

2023-11-08 21:59 UTC, vincentr-wcs commented on public/assets/css/contact.css
> +    font-size: 35px;
idem que plus haut

2023-11-08 21:59 UTC, vincentr-wcs commented on public/assets/css/contact.css
> +    font-family: 'imperial script';
Tu as des variables de disponibles dans root.css et tu les utilises pas ..

2023-11-09 09:32 UTC, vincentr-wcs approved these changes
Super travail !

2023-11-09 09:32 UTC, merged

2023-11-09 09:32 UTC, Jeynox commented
merci @vincentr-wcs